services:
  database:
    image: postgres:17
    container_name: eafc-draft-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - eafc-draft-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: eafc-draft-server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?sslmode=disable
      SERVER_ADDRESS: ${SERVER_ADDRESS}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  eafc-draft-data:
    external: true
